### ISSUE TITLE
segfault in TestSmartCard

### ISSUE THREAD

**Issue by informatimago** [informatimago/FreeRDP-dorian#1]
On branch master:

> Core was generated by '/home/pjb/src/span/sources/informatimago-FreeRDP-dorian/Testing/TestSmartCard'.
> Program terminated with signal SIGSEGV, Segmentation fault.
> #0  __GI___libc_free (mem=0x3236303338383832) at malloc.c:2929
> 2929	malloc.c: No such file or directory.
> (gdb) bt
> #0  __GI___libc_free (mem=0x3236303338383832) at malloc.c:2929
> #1  0x00007f9bd8243b89 in PCSC_RedirectReader (
>     readerName=0xa3e040 "XIRING Leo v2 (8288830623) 00 00")
>     at /home/pjb/src/span/sources/informatimago-FreeRDP-dorian/winpr/libwinpr/smartcard/smartcard_pcsc.c:776
> #2  0x00007f9bd8243c32 in PCSC_ConvertReaderNamesToWinSCard (
>     names=0x2000000000 <error: Cannot access memory at address 0x2000000000>, 
>     pcchReaders=0xa3dfc0)
>     at /home/pjb/src/span/sources/informatimago-FreeRDP-dorian/winpr/libwinpr/smartcard/smartcard_pcsc.c:829
> #3  0x00007f9bd824465b in PCSC_SCardListReaders_Internal (hContext=174017266, 
>     mszGroups=0x0, mszReaders=0x7ffc38959160 "\300ߣ", 
>     pcchReaders=0x7ffc38959150)
>     at /home/pjb/src/span/sources/informatimago-FreeRDP-dorian/winpr/libwinpr/smartcard/smartcard_pcsc.c:1185
> #4  0x00007f9bd8244746 in PCSC_SCardListReadersA (hContext=174017266, 
>     mszGroups=0x0, mszReaders=0x7ffc38959160 "\300ߣ", 
>     pcchReaders=0x7ffc38959150)
>     at /home/pjb/src/span/sources/informatimago-FreeRDP-dorian/winpr/libwinpr/smartcard/smartcard_pcsc.c:1220
> #5  0x00007f9bd823fb5b in SCardListReadersA (hContext=174017266, 
>     mszGroups=0x0, mszReaders=0x7ffc38959160 "\300ߣ", 
>     pcchReaders=0x7ffc38959150)
>     at /home/pjb/src/span/sources/informatimago-FreeRDP-dorian/winpr/libwinpr/smartcard/smartcard.c:75
> #6  0x000000000040118b in TestSmartCardListReaders (argc=0, 
>     argv=0x7ffc389592b0)
>     at /home/pjb/src/span/sources/informatimago-FreeRDP-dorian/winpr/libwinpr/smartcard/test/TestSmartCardListReaders.c:22
> #7  0x0000000000401089 in main (ac=0, av=0x7ffc389592b0)
>     at /home/pjb/src/span/sources/informatimago-FreeRDP-dorian/winpr/libwinpr/smartcard/test/TestSmartCard.c:145
> (gdb)

**Comment by informatimago** [comment]
d705d1bb906d22a5cf0e06dfb5ebc3f2e1f29fc4

**Comment by informatimago** [comment]
Same problem occur in the rework_mapping_smartcard_2 branch.

**Comment by informatimago** [comment]
a556f8edc1092282e468e4febc20c8818c2c3901
